#!/usr/bin/env bash
#script to install all the needed stuff
sudo apt-get update -y
sudo apt-get install emacs -y
sudo apt-get upgrade
sudo apt-get git -y
sudo apt-get install shellcheck -y
sudo apt-get install python3-pep8 -y
sudo apt-get install python3-pip -y
sudo pip3 install pep8
git clone https://github.com/holbertonschool/Betty.git
sudo ./Betty/install.sh
echo 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7-dmr' | sudo tee -a /etc/apt/sources.list
sudo apt-get update -y
sudo apt-get install mysql-server-5.7
sudo apt-get install python3-dev -y
sudo apt-get install libmysqlclient-dev -y
sudo apt-get install zlib1g-dev -y
sudo pip3 install mysqlclient==1.3.10
sudo pip3 install SQLAlchemy==1.2.5
sudo apt-add-repository ppa:brightbox/ruby-ng-experimental
sudo apt-get update -y
sudo apt-get install ruby1.9.3 -y
sudo gem install puppet-lint -y
wget "https://raw.githubusercontent.com/yeungegs/automation-ftw/master/fabricinstall.sh"
chmod u+x fabricinstall.sh
sudo ./fabricinstall.sh
sudo pip3 install Flask
sudo pip3 install flask_cors
